using System.Text;
using Asp.Versioning;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using DotNetEnv;

Env.Load();
var tokenKey = Environment.GetEnvironmentVariable("TOKEN_KEY") ?? throw new Exception("Token key is null");

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddApiVersioning(options =>
{
    // Enable the reporting of the API version in the response header
    options.ReportApiVersions = true;
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.DefaultApiVersion = new ApiVersion(1, 0); // Version 1.0 by default
    options.ApiVersionReader = new UrlSegmentApiVersionReader();
});
// Use openAPI to generate the swagger documentation
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "FirstAPI", Version = "v1" });
});




// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(options =>
{
    options.AddPolicy(
        name: "DevCors",
        corsPolicyBuilder =>
        {
            corsPolicyBuilder.WithOrigins("http://localhost:3000", "https://localhost:4200", "http://localhost:8000") // ports for react, angular, vue
            .AllowAnyMethod()
            .AllowAnyHeader()
            .AllowCredentials();
        }
    );
    options.AddPolicy(
       name: "ProdCors",
       corsPolicyBuilder =>
       {
              corsPolicyBuilder.WithOrigins("https://myproduction.com") // Add your production domain here
              .AllowAnyMethod()
              .AllowAnyHeader()
              .AllowCredentials();
       }
   );

});
builder.Services.AddOutputCache(options =>
{
    options.AddBasePolicy(x => x.Expire(TimeSpan.FromMinutes(5)));
});


// builder.Services.AddScoped<DataContextDapper>();


SymmetricSecurityKey key = new(
    Encoding.UTF8.GetBytes(
        tokenKey
    )
);

TokenValidationParameters tokenValidationParameters = new()
{
    IssuerSigningKey = key,
    ValidateIssuer = false,
    ValidateIssuerSigningKey = false,
    ValidateAudience = false
};

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
{
    options.TokenValidationParameters = tokenValidationParameters;
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseCors("DevCors");
    app.UseSwagger();
    // app.UseSwaggerUI();
    // use the documentation generated by swagger
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "FirstAPI v1");
    });
}else
{
    app.UseCors("ProdCors");
    app.UseHttpsRedirection();

}

app.UseAuthentication();
app.UseAuthorization();
app.UseOutputCache();
app.MapControllers();


app.Run();


/*
MEMO FOR THINGS I LEARNED SO FAR:
- [ApiController] attribute is used to indicate that the class is a controller.
- [Route] attribute is used to define the route for the controller.
- ControllerBase is a base class for MVC controllers. (A SMALLER VERSION OF CONTROLLER)
- IConfiguration is used to access the configuration settings.
- GetConnectionString() method is used to get the connection string from the appsettings.json file. // I NEED TO SEE MORE ABOUT HTTPS
- [HttpGet] attribute is used to define the HTTP GET method.
- I HAVE TO MAKE THE MODEL'S PROPERTIES MATCH THE DATABASE'S COLUMN NAMES

*/

/*
THINGS I WANT TO KNOW WHY:
- WHY WHEN I WAS ON HTTPS, IT SAYS MULTIPLE CONSTRUCTORS FOUND, BUT WHEN I WAS ON HTTP, IT WORKS FINE?
*/

/*
THINGS I WANT TO LEARN MORE ABOUT:
- IConfiguration
- Dependency Injection
- HTTPS
- CORS
- HOW NAMESPACES WORK
*/
